### ISSUE TITLE
Jetson support

### ISSUE THREAD

**Issue by LcungCroooB** [spacewalk01/depth-anything-tensorrt#1]
Does it support Jetson devices? My device environment is as follows:
deepstream-app version 6.0.1
DeepStreamSDK 6.0.1
CUDA Driver Version: 10.2
CUDA Runtime Version: 10.2
TensorRT Version: 8.0
cuDNN Version: 8.2

**Comment by spacewalk01** [comment]
To my knowledge, it should work on jetson devices, as well as ubuntu machine.
