### ISSUE TITLE
 Cuda Runtime (an illegal memory access was encountered)

### ISSUE THREAD

**Issue by chenscottus** [spacewalk01/depth-anything-tensorrt#11]
Hello,

I face the following error when I run it:

1: [reformat.cu::lambda [](dim3, dim3)->auto::operator()::1685] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
3: [executionContext.cpp::nvinfer1::rt::ExecutionContext::enqueueInternal::795] Error Code 3: API Usage Error (Parameter check failed at: executionContext.cpp::nvinfer1::rt::ExecutionContext::enqueueInternal::795, condition: bindings[x] || nullBindingOK

Thanks!

-Scott

**Comment by spacewalk01** [comment]
Will you make sure your input data is correctly set?

**Comment by chenscottus** [comment]
depth_anything.cpp:
float DepthAnything::input_h = 1920;//518;
float DepthAnything::input_w = 1080;// 518;

Working fine now. Thanks!
