### ISSUE TITLE
on my NVIDIA-RTX3090 gpu, time of per frame is 35ms±, is this speed normal?

### ISSUE THREAD

**Issue by silencht** [spacewalk01/depth-anything-tensorrt#12]
good job, thanks your time!

**Comment by silencht** [comment]
my model is Depth-Anything-S. And input video's image size is 640 * 480.

**Comment by spacewalk01** [comment]
Did you use warmup? first few frames will be slow as GPU warms up. Maybe your inference time includes frame merging and overlaying depth on video. I measured only inference time that the time of executing predict function in TRT_Module

**Comment by silencht** [comment]
yes. my command line output as below.
```bash
username@username:~/depth-anything-tensorrt/build$ ./depth-anything-tensorrt depth_anything_vits14.engine /home/username/data1/image/
Time of per frame: 85ms
Time of per frame: 27ms
Time of per frame: 25ms
Time of per frame: 25ms
Time of per frame: 26ms
Time of per frame: 27ms
Time of per frame: 26ms
Time of per frame: 29ms
Time of per frame: 28ms
Time of per frame: 26ms
Time of per frame: 26ms
Time of per frame: 25ms
Time of per frame: 27ms
Time of per frame: 26ms
Time of per frame: 26ms
Time of per frame: 26ms
Time of per frame: 26ms
Time of per frame: 25ms
Time of per frame: 26ms
Time of per frame: 26ms
Time of per frame: 26ms
Time of per frame: 26ms
...omit, because similar like above
```
and when encoder used vitl14, output like this:
```bash
username@username:~/depth-anything-tensorrt/build$ ./depth-anything-tensorrt depth_anything_vitl14.engine /home/username/data1/image/
Time of per frame: 137ms
Time of per frame: 89ms
Time of per frame: 88ms
Time of per frame: 81ms
Time of per frame: 83ms
Time of per frame: 79ms
Time of per frame: 79ms
Time of per frame: 79ms
Time of per frame: 79ms
Time of per frame: 79ms
Time of per frame: 79ms
Time of per frame: 78ms
Time of per frame: 79ms
Time of per frame: 78ms
Time of per frame: 78ms
Time of per frame: 79ms
Time of per frame: 79ms
Time of per frame: 78ms
Time of per frame: 78ms
Time of per frame: 79ms
...omit
```
my computer hardware is  intel i7-11700, 16Gb memory and NVIDIA RTX3090  with 24Gb display memory.
software is Nvidia Driver Version: 535.154.05, CUDA Version: 12.1, TensorRT-8.6.1.6.
I use `trtexec --onnx=depth_anything_vitb14.onnx --saveEngine=depth_anything_vitb14.engine` without `--fp16`
when I run `./depth-anything-tensorrt depth_anything_vitl14.engine /home/username/data1/image/`, I watch my GPU resource with command `gpustat  -a`. It's output like this below,
```bash
[0] NVIDIA GeForce RTX 3090 | 70°C,  61 %,  64 % (E:   0 %  D:   0 %),  331 / 390 W |  2726 / 24576 MB | username:depth-anything-tensorrt/141348(1988M) gdm:Xorg/1208(96M) username:Xorg/1943(351M) username:gnome-shell/2087(55M) username:chrome/124348(70M) username:code/137976(65M) 
```
I replace code `cv::waitKey(100);` of main.cpp to `cv::waitKey(1);`.
GPU Utilization is 60%±（if depth_anything_vits14.engine, this number is 30%±）. I am a freshman for deeplearning inference, so, is this speed normal?

**Comment by spacewalk01** [comment]
Try building engine with TRTModule build and save engine methods by providing onnx model without using trtexec. It will be more lighter.

**Comment by chenscottus** [comment]
Model Input (WxH)
Large model, A6000, 1080x1920, +1000ms per frame.
Small model, A6000, 1080x1920, +1000ms per frame.

**Comment by spacewalk01** [comment]
@silencht Overlaying the depth image on the original image were causing some performance bottleneck on followup inference. I revised it. You may try it again.

**Comment by SoulProficiency** [comment]
> Try building engine with TRTModule build and save engine methods by providing onnx model without using trtexec. It will be more lighter.

how to build engine with TRTModule?can u share the cpp code?

**Comment by spacewalk01** [comment]
You can build an engine from TRTModule and please refer to early commit:
https://github.com/spacewalk01/depth-anything-tensorrt/tree/3868174977d042759c76ac12734ccd3f1fd8628e

**Comment by TouqeerAhmad** [comment]
@spacewalk01 Hello, I am running the C++ pipeline on RTX4090, and ViT-L engine. I am getting a speed of 30ms for an engine exported with FP16. For FP32 precision, I am seeing a speed of 56ms. I have tested for both HD (1920x1080) and 720p (1280x720) resolutions, and get roughly the same numbers, which makes sense as original image gets resized to 518x518 to run inference. 
Do you have any suggestion to investigate it further, as I am seeing a 30ms vs. the reported 12ms in this repo. 
Thanks!
