### ISSUE TITLE
Depth-Anything TensorRT Python

### ISSUE THREAD

**Issue by LWQ2EDU** [spacewalk01/depth-anything-tensorrt#15]
Hi, I have just implemented TensorRT inference in Python based on this project and the [Depth-Anything](https://github.com/LiheYoung/Depth-Anything) project, and by modifying the code in the Depth-Anything, I have also realized a TensorRT inference Gradio demo. May I submit these modifications as a PR to this project?

**Comment by spacewalk01** [comment]
Sure. Send pull request and i will review the code

**Comment by LWQ2EDU** [comment]
> Sure. Send pull request and i will review the code

I will submit the PR ASAP after Chinese New Year. Can't access my computer recently.

**Comment by yuvraj108c** [comment]
@LWQ2EDU Nice work, can you add an example for video inference for python?

**Comment by LWQ2EDU** [comment]
> @LWQ2EDU Nice work, can you add an example for video inference for python?

Nice work, [ComfyUI-Depth-Anything-Tensorrt](https://github.com/yuvraj108c/ComfyUI-Depth-Anything-Tensorrt/tree/master)
