### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by iceriver97** [spacewalk01/depth-anything-tensorrt#20]
![image](https://github.com/spacewalk01/depth-anything-tensorrt/assets/24710426/c67e57ee-c56c-4a25-8c02-fedd00d66de5)
这里depth_data 在新建数组时，需要input_h及input_w 为整形，否则会报错；

**Comment by spacewalk01** [comment]
https://github.com/spacewalk01/depth-anything-tensorrt/blob/6ea63a93b81c03958a6cf2a73c49f2fd739ceae1/depth_anything.cpp#L50

**Comment by spacewalk01** [comment]
thanks pointing this out. casted to integer

**Comment by spacewalk01** [comment]
Tested with following code it doesn't throw error though!

```
#include <iostream>
#include <vector>

int main() {
    float n = 4;

    float* data;

    data = new float[n];

    for (int i = 0; i < n; i++)
    {
        data[i] = i * 10;
    }

    for (int i = 0; i < n; i++)
    {
        std::cout << data[i] << std::endl;
    }

    return 0;
}
```
