### ISSUE TITLE
How to export onnx with dynamic shape?

### ISSUE THREAD

**Issue by HSQ79815** [spacewalk01/depth-anything-tensorrt#22]

**Comment by spacewalk01** [comment]
Currently doesn't support dynamic shape.

**Comment by spacewalk01** [comment]
But you can create your model based on your video resolution as follows:

`python export.py --encoder vitb --load_from depth_anything_vitb14.pth --image_shape 3 video_height video_width`

**Comment by deepfree2023** [comment]
> But you can create your model based on your video resolution as follows:
> 
> `python export.py --encoder vitb --load_from depth_anything_vitb14.pth --image_shape 3 video_height video_width`

The depth map produced by tensorrt was obviuosly blurry and lower quality comparing to the original pth version, is there any means to improve?

I've tried the following steps to use the model at a higher resolution, but failed.

1. python export_v2.py --encoder vitl --input-size 1022 (or some value other than 518, but  divisible by 14)
2. convert the result vitl onnx file to engine file using exportrt.py in this repo:
https://github.com/yuvraj108c/ComfyUI-Depth-Anything-Tensorrt
3. Load the engine file in comfyui and run, then get some errors like tensor shape mismatch, wanted (3,518,518), but get (3, 1022, 1022)
