### ISSUE TITLE
Unable to create engine from onnx model

### ISSUE THREAD

**Issue by xa1on** [spacewalk01/depth-anything-tensorrt#26]
I've prepared the baseline onnx model, however, whenever I try and run depth-anything-tensorrt.exe, it outputs:
```
Loading model from models/depth_anything_vitb14.onnx...
```
and then, the program exits without any errors at all.

This is the command I'm using:
```
build/Release/depth-anything-tensorrt.exe models/depth_anything_vitb14.onnx video/davis_dolphins.mp4
```
I'm assuming that I am exporting the onnx model properly, however, just in case, I'll upload a log. Here's the command I used
```
python export.py --encoder vitb --load_from depth_anything_vitb14.pth --image_shape 3 518 518
```

[onnxmodelexportlog.txt](https://github.com/spacewalk01/depth-anything-tensorrt/files/14849803/onnxmodelexportlog.txt)

Anyone have any idea why this isn't working for me?
Thanks.

CUDA: 11.6
TensortRT: 8.6.1.6
Windows: 11

**Comment by spacewalk01** [comment]
Did you put opencv_worldxxx.dll file in build/Release folder?

**Comment by spacewalk01** [comment]
![image](https://github.com/spacewalk01/depth-anything-tensorrt/assets/6389915/59d2825e-8f9a-4897-81cb-e71044850877)

**Comment by spacewalk01** [comment]
Also add video io dll files
![image](https://github.com/spacewalk01/depth-anything-tensorrt/assets/6389915/f40c92e4-cd32-4b50-915b-436085a78823)

**Comment by spacewalk01** [comment]
Let me know if it works. Please give a star if you like the project and my help.

**Comment by xa1on** [comment]
I've already starred the project, however, even with the DLL files, the same issue is still present. I'm still not getting any errors and no engine file is being built.

**Comment by xa1on** [comment]
> Let me know if it works. Please give a star if you like the project and my help.

![image](https://github.com/spacewalk01/depth-anything-tensorrt/assets/82491956/edce2dfa-9843-424b-bb05-83b0171ea202)

**Comment by xa1on** [comment]
I've also been trying to build the engine file with trtexec with an [older version](https://github.com/spacewalk01/depth-anything-tensorrt/tree/bbda9d2478b4fb3c11506d73f2392aa8c43dd9d1?tab=readme-ov-file) of this repo, however, I'm still running into issues.
I'm following this [guide](https://github.com/spacewalk01/depth-anything-tensorrt/issues/14#issue-2113875896), however, I keep running into a "network creation failed" error in trtexec.
My issue is outlined [here](https://forums.developer.nvidia.com/t/unable-to-convert-onnx-model-to-engine-w-trtexec-network-creation-failed/288502) with all the relevant files

**Comment by xa1on** [comment]
> Let me know if it works. Please give a star if you like the project and my help.

thank you for taking the time to read my issue, your work looks amazing, however, I hope you're still able to help me with this :D

**Comment by spacewalk01** [comment]
did you modify [CMakeLists.txt](https://github.com/spacewalk01/depth-anything-tensorrt/blob/main/CMakeLists.txt) to set your opencv and tensorrt paths?
![image](https://github.com/spacewalk01/depth-anything-tensorrt/assets/6389915/cf4559f0-6de0-4940-9498-967cb8e5714e)

**Comment by spacewalk01** [comment]
Please just use the most recent version and let's try to fix  your issue.

**Comment by spacewalk01** [comment]
I checked your [onnxmodelexportlog.txt](https://github.com/spacewalk01/depth-anything-tensorrt/files/14849803/onnxmodelexportlog.txt) file. It seems your engine is correctly built.

**Comment by xa1on** [comment]
> did you modify [CMakeLists.txt](https://github.com/spacewalk01/depth-anything-tensorrt/blob/main/CMakeLists.txt) to set your opencv and tensorrt paths? ![image](https://private-user-images.githubusercontent.com/6389915/320692129-cf4559f0-6de0-4940-9498-967cb8e5714e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MjY0MTUsIm5iZiI6MTcxMjYyNjExNSwicGF0aCI6Ii82Mzg5OTE1LzMyMDY5MjEyOS1jZjQ1NTlmMC02ZGUwLTQ5NDAtOTQ5OC05NjdjYjhlNTcxNGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMDEyODM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDAzODZhN2YwMzU1ZTFlOTJlMTg4NGE0Njc3ZmE1M2EwNTdhZjI5ZDgxNzIyMjAyNjdlNjVmYmY4YjFlMGU3ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BFf_xq4v7QG_ioVLSPV2VTvkESC9EHJrpdWitvfglnE)

I have modified that file to the correct paths:
![image](https://github.com/spacewalk01/depth-anything-tensorrt/assets/82491956/09b566ae-92a0-40d4-a499-3711e84b9081)

**Comment by spacewalk01** [comment]
That is very strange. It should show an error if there is a bug or problem in the code. If it doesn't show it may be system error

**Comment by spacewalk01** [comment]
Or premission. you tensorrt and opencv are in c folder will you try it as admin?

**Comment by xa1on** [comment]
I'm sorry I can't provide any further information, but yeah, it still doesn't work.
![image](https://github.com/spacewalk01/depth-anything-tensorrt/assets/82491956/c912c09c-c9bf-4fff-8847-d2a1e25d902c)

**Comment by spacewalk01** [comment]
What is your gpu?

**Comment by xa1on** [comment]
I have a mobile NVIDIA GTX 1060 3gb vram
![image](https://github.com/spacewalk01/depth-anything-tensorrt/assets/82491956/f39d93b1-9f64-4f5f-9eec-483686c0c46d)

**Comment by spacewalk01** [comment]
I used your onnx model you put [here](https://forums.developer.nvidia.com/t/unable-to-convert-onnx-model-to-engine-w-trtexec-network-creation-failed/288502) and created the engine successfully. I think there is a cuda version problem in your system. maybe your cuda 11.6 version is not suitable for your GPU. I will look it up for you.
![image](https://github.com/spacewalk01/depth-anything-tensorrt/assets/6389915/4e2d93c3-7f86-4870-b976-7e7ecefacbd6)

**Comment by xa1on** [comment]
I have been able to successfully run the onnx model with cuda acceleration from this [repo](https://github.com/fabio-sim/Depth-Anything-ONNX).
I don't think that compatibility with the cuda version is the issue. It could be possible that my gpu just does not support tensorrt

**Comment by spacewalk01** [comment]
I found out that Compute capability (version) for your GPU (nvidia gtx 1060) is  6.1

**Comment by spacewalk01** [comment]
Also, I checked that compute capability 6.1 pascal arch is compitable with CUDA 8.0
![image](https://github.com/spacewalk01/depth-anything-tensorrt/assets/6389915/d3bcc017-cc21-4689-acfc-b74dfbd3bbc5)

**Comment by spacewalk01** [comment]
Please install cuda 8.0. Also don't forget to install cudnn version for cuda8.0

**Comment by xa1on** [comment]
![image](https://github.com/spacewalk01/depth-anything-tensorrt/assets/82491956/8f75d175-d68b-4289-9c06-4c7c3d90d567)

nvidia-smi states that my current cuda version is 12.4 which should allow me to use cuda version 11.6.
I have been able to use version 11.6 with this [repo](https://github.com/fabio-sim/Depth-Anything-ONNX) too.

Let me try it out though.

**Comment by spacewalk01** [comment]
Then check your onnx cuda version what version it is installed with?

**Comment by xa1on** [comment]
could you explain what you mean by onnx cuda version? I was able to use version 11.6 with this [repo](https://github.com/fabio-sim/Depth-Anything-ONNX).

**Comment by spacewalk01** [comment]
Mine says I am using cuda12.0 but in fact I installed 11.8. It doesn't show cuda toolkit version
![image](https://github.com/spacewalk01/depth-anything-tensorrt/assets/6389915/525814f0-ac98-41cc-a8c7-b5a98417044e)

**Comment by xa1on** [comment]
yes, but it should indicate that my current driver is using cuda version 12.4. I have installed the latest Nvidia driver for my gpu.

**Comment by spacewalk01** [comment]
You used `pip install onnxruntime-gpu` command to install onnx gpu right? use conda list to check onnxruntime-gpu version. Then you can check here which onnxruntime version is installed with which cuda version. https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html  it automatically install cuda toolkit

**Comment by xa1on** [comment]
![image](https://github.com/spacewalk01/depth-anything-tensorrt/assets/82491956/59df3b35-c5d2-44b6-afdf-eaae43e7d1fa)
![image](https://github.com/spacewalk01/depth-anything-tensorrt/assets/82491956/0727ee84-6d4b-48c4-9a19-4a7862bb4f9c)
![image](https://github.com/spacewalk01/depth-anything-tensorrt/assets/82491956/57621ed0-ac1f-42bd-82ae-39b633b81424)
I should have version 11.6 installed properly, I will check with onnxruntime-gpu in a second

**Comment by spacewalk01** [comment]
for my case it automatically install onnxruntime version that suitable for my gpu which is suitable for cuda 11.8
![image](https://github.com/spacewalk01/depth-anything-tensorrt/assets/6389915/f529c222-07cb-46a4-84c9-584883bc5166)

**Comment by spacewalk01** [comment]
onnxruntime is different it will use anaconda environment to install cuda. I suggest you to install cuda 8.0 and do the steps again.

**Comment by xa1on** [comment]
I will try that, but again, I have been able to use my version of the onnxruntime with my current version of cuda with cuda acceleration just fine in the past with the exact same model through this [repo](https://github.com/fabio-sim/Depth-Anything-ONNX).

**Comment by spacewalk01** [comment]
Hmm sorry that is what I can suggest from my observation. I can't guess without looking at it

**Comment by xa1on** [comment]
I am looking at the onnx [website](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html) you sent me and it seems to be suggesting that only cuda versions 10 and up are supported.

**Comment by xa1on** [comment]
I'm kind of confused because I've been able to use the onnx runtime with cuda enabled before

**Comment by xa1on** [comment]
> Hmm sorry that is what I can suggest from my observation. I can't guess without looking at it

I've completely redownloaded my cuda and tensorrt. Now I'm getting an error stating:
```Loading model from models/vitb14.onnx...
onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
onnx2trt_utils.cpp:400: One or more weights outside the range of INT32 was clamped
4: [network.cpp::nvinfer1::Network::validate::3163] Error Code 4: Internal Error (Network has dynamic or shape inputs, but no optimization profile has been defined.)```

**Comment by xa1on** [comment]
I've figured it out. It was either my cuda cudnn or tensorrt installation that was the problem. I reinstalled everything and it works now.

Thanks for all your help!

**Comment by spacewalk01** [comment]
It works on 11.6 cuda version with nvidia gtx 1060 ?

**Comment by xa1on** [comment]
> It works on 11.6 cuda version with nvidia gtx 1060 ?

I reinstalled everything and used cuda 11.8 for my gpu. I believe the problem was the cudnn installation.

**Comment by spacewalk01** [comment]
I see.
