### ISSUE TITLE
About on Jetson orin

### ISSUE THREAD

**Issue by cchester25** [spacewalk01/depth-anything-tensorrt#27]
Thank you very much for your work. I successfully obtained ONNX on the Jetson Orin platform according to your process. However, when I used this ONNX for depth estimation, I encountered the error "Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64." Attempting to cast down to INT32
Onnx2tr_utils. cpp: 403: One or more weights outside the range of INT32 was clamped
Tactical Device request: 19043MB Available: 15974MB Device memory is ineffective to use tactic
Skipping tactic 3 due to insufficient memory on requested size of 19043 detected for tactic 0x0000000 4
Try decreasing the workspace size with BuilderConfiguration:: setMemoryPoolLimit() ”
May I ask what I should do?

**Comment by spacewalk01** [comment]
Hi, "`our ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64`" message is  warning [W] not error [E]. But the second one looks like the actual error.  I haven't tried on Jetson but as it says device memory seems insufficient (out of memory I guess). Will you try the smallest model [depth_anything_vits14.pth](https://huggingface.co/spaces/LiheYoung/Depth-Anything/blob/main/checkpoints/depth_anything_vits14.pth)? Also there is a similar [problem here](https://github.com/NVIDIA/TensorRT/issues/3355). Another [one](https://github.com/ultralytics/yolov5/issues/12637).

**Comment by spacewalk01** [comment]
Also you can increase `Max Workspace Size` using the following function when you build your engine:        

`builder->setMaxWorkspaceSize(1 << 30);// 1G`
or
`config->setMaxWorkspaceSize(24 * (1ULL << 30));`


Make sure to put it after you create a builder instance.

**Comment by cchester25** [comment]
Hello, I have adopted your suggestion to use the smallest model and set `config ->setMaxWorkspaceSize (24 * (1ULL<<30));` A warning of INT64->INT32 and "`Onnx2tr_utils. cpp: 403: One or more weights outside the range of INT32 `was jammed" appeared, and the model initialization was blocked at the `IHostMemory * plan {builder ->buildSerialized Network (* network, * config)} `in the function "`void DepthAnything:: build (std:: string onnxPath, nvinfer1:: ILogger&logger)`";. I don't quite understand what caused the blockage. Could you please give some suggestions.

> Also you can increase `Max Workspace Size` using the following function when you build your engine:
> 
> `builder->setMaxWorkspaceSize(1 << 30);// 1G` or `config->setMaxWorkspaceSize(24 * (1ULL << 30));`
> 
> Make sure to put it after you create a builder instance.

**Comment by spacewalk01** [comment]
Please put here full log message

**Comment by cchester25** [comment]
> Please put here full log message
This is my log message, and I have printed a prompt message after each step is completed
![微信图片_20240422155557](https://github.com/spacewalk01/depth-anything-tensorrt/assets/70146927/9e6293db-738c-405f-8d5b-044c1c3428d9)
This is the content I modified in the code
![code](https://github.com/spacewalk01/depth-anything-tensorrt/assets/70146927/0faada6f-17ce-4130-a3ce-edd82619e5bc)

**Comment by spacewalk01** [comment]
Here is the message I got:
```
Loading model from depth_anything_vits14.onnx...
CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
onnx2trt_utils.cpp:400: One or more weights outside the range of INT32 was clamped
Detected layernorm nodes in FP16: /blocks.0/norm2/ReduceMean_1, /blocks.1/norm2/ReduceMean_1, /blocks.3/norm1/ReduceMean_1, /blocks.1/norm1/ReduceMean_1, /blocks.2/norm1/ReduceMean_1, /blocks.4/norm1/ReduceMean_1, /blocks.3/norm2/ReduceMean_1, /blocks.2/norm2/ReduceMean_1, /blocks.0/norm1/ReduceMean_1, /blocks.6/norm2/ReduceMean_1, /blocks.9/norm2/ReduceMean_1, /blocks.5/norm2/ReduceMean_1, /blocks.9/norm1/ReduceMean_1, /blocks.7/norm1/ReduceMean_1, /blocks.10/norm1/ReduceMean_1, /blocks.6/norm1/ReduceMean_1, /blocks.4/norm2/ReduceMean_1, /blocks.10/norm2/ReduceMean_1, /blocks.8/norm1/ReduceMean_1, /norm_2/ReduceMean_1, /norm_1/ReduceMean_1, /blocks.8/norm2/ReduceMean_1, /norm/ReduceMean_1, /blocks.11/norm1/ReduceMean_1, /blocks.5/norm1/ReduceMean_1, /blocks.11/norm2/ReduceMean_1, /blocks.7/norm2/ReduceMean_1, /norm_3/ReduceMean_1, /blocks.0/norm1/Pow, /blocks.0/norm1/Mul, /blocks.0/norm1/Div, /blocks.0/norm1/Sub, /blocks.0/norm1/Add, /blocks.0/norm1/Add_1, /blocks.1/norm1/Add, /blocks.1/norm2/Add, /blocks.1/norm2/Pow, /blocks.1/norm1/Add_1, /blocks.1/norm2/Div, /blocks.1/norm2/Add_1, /blocks.2/norm1/Add, /blocks.2/norm1/Add_1, /blocks.2/norm2/Div, /blocks.0/norm2/Pow, /blocks.1/norm2/Sub, /blocks.0/norm2/Sub, /blocks.2/norm1/Mul, /blocks.2/norm2/Add, /blocks.0/norm2/Add_1, /blocks.2/norm1/Div, /blocks.2/norm2/Mul, /blocks.0/norm2/Mul, /blocks.1/norm1/Pow, /blocks.1/norm1/Div, /blocks.0/norm2/Div, /blocks.1/norm1/Sub, /blocks.1/norm2/Mul, /blocks.2/norm2/Pow, /blocks.0/norm2/Add, /blocks.1/norm1/Mul, /blocks.2/norm2/Sub, /blocks.2/norm1/Sub, /blocks.2/norm1/Pow, /blocks.2/norm2/Add_1, /blocks.3/norm1/Add_1, /blocks.3/norm1/Pow, /blocks.3/norm1/Div, /blocks.3/norm2/Sub, /blocks.3/norm2/Pow, /blocks.3/norm1/Sub, /blocks.3/norm1/Mul, /blocks.3/norm1/Add, /blocks.10/norm2/Sqrt, /blocks.7/norm1/Sqrt, /blocks.4/norm2/Sqrt, /blocks.2/norm1/Sqrt, /blocks.4/norm1/Sqrt, /blocks.6/norm1/Sqrt, /blocks.11/norm2/Sqrt, /blocks.9/norm1/Sqrt, /blocks.1/norm2/Sqrt, /blocks.1/norm1/Sqrt, /blocks.6/norm2/Sqrt, /blocks.3/norm2/Sqrt, /blocks.10/norm1/Sqrt, /blocks.9/norm2/Sqrt, /blocks.2/norm2/Sqrt, /blocks.0/norm2/Sqrt, /blocks.7/norm2/Sqrt, /blocks.8/norm2/Sqrt, /blocks.5/norm1/Sqrt, /blocks.3/norm1/Sqrt, /blocks.8/norm1/Sqrt, /blocks.5/norm2/Sqrt, /norm_1/Sqrt, /blocks.11/norm1/Sqrt, /norm_2/Sqrt, /norm/Sqrt, /norm_3/Sqrt, /blocks.0/norm1/Sqrt, /blocks.3/norm2/Mul, /blocks.3/norm2/Add_1, /blocks.4/norm1/Pow, /blocks.4/norm2/Div, /blocks.3/norm2/Add, /blocks.5/norm1/Div, /blocks.5/norm1/Mul, /blocks.4/norm2/Pow, /blocks.5/norm2/Div, /blocks.4/norm2/Mul, /blocks.4/norm1/Div, /blocks.3/norm2/Div, /blocks.4/norm1/Add_1, /blocks.5/norm2/Add_1, /blocks.5/norm1/Sub, /blocks.5/norm1/Add, /blocks.4/norm1/Add, /blocks.6/norm1/Sub, /blocks.5/norm2/Pow, /blocks.4/norm2/Add, /blocks.5/norm2/Sub, /blocks.4/norm2/Sub, /blocks.5/norm2/Add, /blocks.6/norm1/Pow, /blocks.4/norm1/Mul, /blocks.4/norm1/Sub, /blocks.5/norm1/Add_1, /blocks.4/norm2/Add_1, /blocks.5/norm1/Pow, /blocks.5/norm2/Mul, /blocks.6/norm2/Pow, /blocks.8/norm2/Sub, /blocks.7/norm1/Add, /blocks.6/norm1/Add_1, /blocks.7/norm2/Div, /blocks.6/norm2/Sub, /blocks.6/norm2/Add_1, /blocks.7/norm1/Div, /blocks.7/norm1/Sub, /blocks.6/norm1/Mul, /blocks.8/norm1/Add, /blocks.7/norm1/Mul, /blocks.8/norm1/Add_1, /blocks.6/norm2/Add, /blocks.6/norm2/Div, /blocks.6/norm1/Add, /blocks.6/norm1/Div, /blocks.6/norm2/Mul, /blocks.7/norm2/Sub, /blocks.7/norm2/Add, /blocks.8/norm1/Sub, /blocks.7/norm2/Pow, /blocks.7/norm1/Add_1, /blocks.7/norm2/Mul, /blocks.7/norm1/Pow, /blocks.7/norm2/Add_1, /blocks.8/norm1/Pow, /blocks.8/norm2/Pow, /blocks.8/norm2/Div, /blocks.8/norm2/Mul, /blocks.8/norm1/Mul, /blocks.8/norm1/Div, /blocks.8/norm2/Add, /blocks.9/norm1/Add_1, /blocks.9/norm2/Sub, /blocks.9/norm2/Pow, /blocks.9/norm2/Mul, /blocks.9/norm2/Add_1, /blocks.9/norm1/Div, /blocks.8/norm2/Add_1, /blocks.10/norm1/Pow, /blocks.10/norm1/Sub, /blocks.9/norm2/Div, /blocks.9/norm1/Add, /blocks.9/norm1/Pow, /norm_1/Div, /blocks.10/norm1/Mul, /blocks.10/norm1/Add, /blocks.10/norm1/Div, /blocks.10/norm1/Add_1, /norm/Pow, /norm_1/Sub, /norm/Sub, /norm_1/Pow, /norm_1/Add, /norm/Add_1, /blocks.10/norm2/Pow, /blocks.10/norm2/Sub, /blocks.10/norm2/Add, /blocks.10/norm2/Div, /blocks.9/norm2/Add, /blocks.10/norm2/Mul, /blocks.9/norm1/Sub, /norm/Add, /norm/Mul, /norm_1/Add_1, /norm_1/Mul, /blocks.9/norm1/Mul, /norm/Div, /blocks.11/norm1/Div, /blocks.11/norm2/Pow, /blocks.11/norm2/Mul, /blocks.11/norm2/Add_1, /norm_3/Pow, /norm_3/Div, /norm_3/Add_1, /blocks.11/norm1/Pow, /blocks.11/norm2/Sub, /norm_2/Div, /blocks.11/norm1/Sub, /blocks.11/norm1/Add_1, /norm_3/Add, /norm_3/Mul, /norm_2/Add, /blocks.11/norm2/Div, /norm_3/Sub, /blocks.10/norm2/Add_1, /blocks.11/norm2/Add, /norm_2/Sub, /norm_2/Pow, /norm_2/Mul, /norm_2/Add_1, /blocks.11/norm1/Mul, /blocks.11/norm1/Add
Running layernorm after self-attention in FP16 may cause overflow. Forcing layernorm layers to run in FP32 precision can help with preserving accuracy.
TensorRT encountered issues when converting weights between types and that could affect accuracy.
If this is not the desired behavior, please modify the weights or retrain with regularization to adjust the magnitude of the weights.
Check verbose logs for the list of affected weights.
- 123 weights are affected by this issue: Detected subnormal FP16 values.
- 42 weights are affected by this issue: Detected values less than smallest positive FP16 subnormal value and converted them to the FP16 minimum subnormalized value.
CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
The model has been successfully loaded!
```

**Comment by spacewalk01** [comment]
First these lines are warnings you can ignore them:
```
CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
onnx2trt_utils.cpp:400: One or more weights outside the range of INT32 was clamped
```

**Comment by spacewalk01** [comment]
> Hello, I have adopted your suggestion to use the smallest model and set `config ->setMaxWorkspaceSize (24 * (1ULL<<30));` A warning of INT64->INT32 and "`Onnx2tr_utils. cpp: 403: One or more weights outside the range of INT32 `was jammed" appeared, and the model initialization was blocked at the `IHostMemory * plan {builder ->buildSerialized Network (* network, * config)} `in the function "`void DepthAnything:: build (std:: string onnxPath, nvinfer1:: ILogger&logger)`";. I don't quite understand what caused the blockage. Could you please give some suggestions.
> 
> > Also you can increase `Max Workspace Size` using the following function when you build your engine:
> > `builder->setMaxWorkspaceSize(1 << 30);// 1G` or `config->setMaxWorkspaceSize(24 * (1ULL << 30));`
> > Make sure to put it after you create a builder instance.

It is not blocked I think. Building engine takes time. Wait for it

**Comment by cchester25** [comment]
> > Hello, I have adopted your suggestion to use the smallest model and set `config ->setMaxWorkspaceSize (24 * (1ULL<<30));` A warning of INT64->INT32 and "`Onnx2tr_utils. cpp: 403: One or more weights outside the range of INT32 `was jammed" appeared, and the model initialization was blocked at the `IHostMemory * plan {builder ->buildSerialized Network (* network, * config)} `in the function "`void DepthAnything:: build (std:: string onnxPath, nvinfer1:: ILogger&logger)`";. I don't quite understand what caused the blockage. Could you please give some suggestions.
> > > Also you can increase `Max Workspace Size` using the following function when you build your engine:
> > > `builder->setMaxWorkspaceSize(1 << 30);// 1G` or `config->setMaxWorkspaceSize(24 * (1ULL << 30));`
> > > Make sure to put it after you create a builder instance.
> 
> It is not blocked I think. Building engine takes time. Wait for it

Thank you for your suggestion！it is indeed effective for me. I understand the cause of my problem. I have one final question, is it necessary to build an engine every time a depth estimation task is executed, after all, building an engine takes a long time every time the program starts.

**Comment by spacewalk01** [comment]
Nope! Once you've built your engine, the next time you run it, simply use your engine file instead of the ONNX file
```
>depth-anything-tensorrt.exe depth_anything_vitb14.engine data
```

**Comment by spacewalk01** [comment]
If you like my help, please support me by starring the project. Thanks :)

**Comment by cchester25** [comment]
> If you like my help, please support me by starring the project. Thanks :)

Of course！actually, I started your project first and then tried it out. Thank you again for your contribution.

**Comment by spacewalk01** [comment]
Thank you
