### ISSUE TITLE
Engine generated is for Relative Depth or Metric Depth?

### ISSUE THREAD

**Issue by a-kungwani** [spacewalk01/depth-anything-tensorrt#29]
Hi @spacewalk01, the existing process in your repository generates the engine for relative depth or Metric Depth?

Thank you in advance
Aman

**Comment by lbq779660843** [comment]
Relative depth. If you want to get metric depth you can refer [link1](https://github.com/LiheYoung/Depth-Anything/issues/36) and [link2](https://github.com/LiheYoung/Depth-Anything/tree/1e1c8d373ae6383ef6490a5c2eb5ef29fd085993/metric_depth).

**Comment by a-kungwani** [comment]
I already implemented the [Depth anything metric depth](https://github.com/LiheYoung/Depth-Anything/tree/1e1c8d373ae6383ef6490a5c2eb5ef29fd085993/metric_depth)h. I also want to implement the Depth anything TensorRT but to get the metric depth using TensorRT

**Comment by lbq779660843** [comment]
Great! We're here to look forward to your good news. Feel free to reopen the issue if you can share more details or any specific observations you have found.

**Comment by sctrueew** [comment]
@a-kungwani Hi,

Have you managed to solve it? I was able to convert the outdoor metric model to a .engine file, but the output isn't correct.
