### ISSUE TITLE
metric_depth模型怎么使用tensorrt进行推理

### ISSUE THREAD

**Issue by gopin95** [spacewalk01/depth-anything-tensorrt#31]
metric_depth模型怎么使用tensorrt进行推理

**Comment by spacewalk01** [comment]
currently metric_depth model is not integrated into this repo. sorry.

**Comment by gopin95** [comment]
请问大概什么时候可以集合呢？

spacewalk01 ***@***.***>于2024年6月12日 周三下午3:54写道：
