### ISSUE TITLE
Compatibility with TensorRT Version 10

### ISSUE THREAD

**Issue by junwon-seo716** [spacewalk01/depth-anything-tensorrt#34]
First, I want to thank @spacewalk01 for your contributions to this project. With the recent update to NVIDIA's TensorRT to version 10, there have been several significant changes to the APIs. For instance, the function getBindingDimensions has been removed, and it is recommended to use getTensorShape instead. Additionally, other C++ APIs like enqueueV2 are no longer available. (https://docs.nvidia.com/deeplearning/tensorrt/migration-guide/index.html)

I am curious to know if there are any plans to update the project's code to ensure compatibility with TensorRT version 10. As many users transition to the latest version, updating for compatibility becomes increasingly important. Could you share if there is an ongoing plan for this?

Thank you for your attention to this matter.

**Comment by spacewalk01** [comment]
Thank you. Personally i havent used tensorrt 10. it seems api is changed a
lot. I will try to add tensorrt10 version as soon as possible.

**Comment by junwon-seo716** [comment]
Thank you for your quick response and for considering the update to TensorRT version 10. I appreciate your willingness to adapt the project to the new API changes. Looking forward to seeing the updates when they're ready. Thanks again for your efforts!

**Comment by spacewalk01** [comment]
Hi added support for tensorrt 10. 
Note that it was tested on `TensorRT-10.0.1.6` with `CUDA 11.8` on Windows 10 machine. Let me know if there is any problem.

**Comment by junwon-seo716** [comment]
Hi, Thank you for adding support for TensorRT 10 so quickly! I've tested the updated code on Ubuntu 22.04 with TensorRT-10.1.0.27 and CUDA 12.2, and it works well. However, I noticed a small modification is needed in the CMakeLists.txt file to ensure compatibility with this setup on Ubuntu (maybe). Instead of specifying version numbers in the libraries:

set(TENSORRT_LIBS nvinfer_10 nvinfer_plugin_10 nvonnxparser_10)
It should be:

set(TENSORRT_LIBS nvinfer nvinfer_plugin nvonnxparser)
This change might help others using the latest versions. Thanks again for your efforts and support!

**Comment by spacewalk01** [comment]
I see. In windows nvinfer_10 is correct as they added 10 at the end of library names. I see that on ubuntu they added 10 after so like libnvinfer.so.10. I will try to modify it for ubuntu.

**Comment by spacewalk01** [comment]
fixed it. now it will set libraries based on OS win or linux as well as tensorrt version you are using. Let me know it works without modification.

**Comment by junwon-seo716** [comment]
I tested your code and it works well. Thanks!
